import type { Metadata } from "next";
import Link from "next/link";
import LegalHeader from "@/app/components/LegalHeader";

export const metadata: Metadata = {
  title: "Terms of Service — highyield.cards",
  description: "Terms of service and refund policy for highyield.cards.",
};

const LAST_UPDATED = "June 12, 2026";

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-[#f7f5f0]">
      <LegalHeader />
      <main className="flex-1 w-full max-w-xl mx-auto px-6 py-12 sm:py-16">
        <h1 className="font-serif text-3xl text-[#1a2820] mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-8">Last updated: {LAST_UPDATED}</p>

        <div className="space-y-8 text-[15px] leading-relaxed text-slate-700">
          <section>
            <h2 className="font-serif text-xl text-[#1a2820] mb-2">1. The service</h2>
            <p>
              highyield.cards turns documents you provide into Anki flashcard decks using AI. By
              using the service you agree to these terms. If you don&rsquo;t agree, don&rsquo;t use
              the service.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#1a2820] mb-2">2. Your content</h2>
            <p>
              You keep all rights to the documents you upload and the decks generated from them.
              You may only upload content you have the right to use — your own notes, materials
              you&rsquo;re licensed to use, or content in the public domain. You grant us a limited
              license to process your documents solely to generate your decks, including
              transmitting their text to Google&rsquo;s Gemini API as described in our{" "}
              <Link href="/privacy" className="underline text-[#7a4f0d]">Privacy Policy</Link>. We
              do not store your documents after your request completes.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#1a2820] mb-2">3. AI-generated output</h2>
            <p>
              Flashcards are generated by an AI model and may contain errors or omissions. They are
              a study aid, not a substitute for your source material. Verify anything you rely on —
              especially for exams, clinical, legal, or safety-related subjects.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#1a2820] mb-2">4. Plans and payments</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong>Free tier.</strong> A limited number of deck generations per month with a
                document size cap. Limits may change.
              </li>
              <li>
                <strong>One-time purchase.</strong> A single payment that grants a fixed number of
                deck generation credits at a higher document size cap. Credits don&rsquo;t expire.
                If a generation fails, the credit is automatically returned to you.
              </li>
              <li>
                <strong>Pro subscription.</strong> A recurring subscription with unlimited
                generations and higher limits. It renews automatically until cancelled. You can
                cancel anytime; access continues through the end of the period you&rsquo;ve paid
                for.
              </li>
            </ul>
            <p className="mt-2">
              Payments are processed by Stripe. Prices are shown before you pay and may change for
              future purchases; changes never affect a period you&rsquo;ve already paid for.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#1a2820] mb-2">5. Refund policy</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong>One-time purchases:</strong> if you&rsquo;re unhappy for any reason, contact
                us within 14 days of purchase via the{" "}
                <a href="https://tally.so/r/b5YPre" className="underline text-[#7a4f0d]" target="_blank" rel="noopener noreferrer">contact form</a>{" "}
                and we&rsquo;ll refund you in full. Refunds are issued to your original payment
                method; remaining credits are removed when the refund is processed.
              </li>
              <li>
                <strong>Subscriptions:</strong> cancelling stops future charges, and you keep
                access until the end of the current billing period. If you were charged in error
                or charged for a renewal you didn&rsquo;t want, contact us within 14 days of the
                charge and we&rsquo;ll refund it.
              </li>
              <li>
                <strong>Failed generations:</strong> credits consumed by a failed generation are
                returned automatically — no request needed.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#1a2820] mb-2">6. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>upload content that infringes someone else&rsquo;s rights or is unlawful;</li>
              <li>attempt to circumvent rate limits, plan limits, or payment requirements;</li>
              <li>probe, disrupt, or overload the service or its infrastructure;</li>
              <li>resell or redistribute the service itself without our permission.</li>
            </ul>
            <p className="mt-2">
              We may suspend or terminate access for violations of these terms.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#1a2820] mb-2">7. Availability and changes</h2>
            <p>
              The service is provided &ldquo;as is&rdquo; and &ldquo;as available.&rdquo; We work to
              keep it reliable, but we don&rsquo;t guarantee uninterrupted operation, and we may
              change or discontinue features. If we discontinue the service entirely, we&rsquo;ll
              refund any unused one-time credits and the unused portion of any active
              subscription.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#1a2820] mb-2">8. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, we are not liable for indirect, incidental,
              or consequential damages arising from your use of the service, and our total
              liability for any claim is limited to the amount you paid us in the twelve months
              before the claim arose. Nothing in these terms limits liability that cannot be
              limited by law.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#1a2820] mb-2">9. Changes to these terms</h2>
            <p>
              We may update these terms; the date above reflects the latest version. Material
              changes will be noted on the site. Continuing to use the service after a change
              means you accept the updated terms.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#1a2820] mb-2">10. Contact</h2>
            <p>
              Questions, refund requests, or anything else: reach us through the{" "}
              <a href="https://tally.so/r/b5YPre" className="underline text-[#7a4f0d]" target="_blank" rel="noopener noreferrer">contact form</a>.
            </p>
          </section>
        </div>

        <p className="mt-12 text-sm text-slate-500">
          See also our{" "}
          <Link href="/privacy" className="text-[#7a4f0d] underline underline-offset-2">
            Privacy Policy
          </Link>
          .
        </p>
      </main>
    </div>
  );
}
